### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by ArotaesForgehammer** [Evolution0/bandcamp-dl#100]
**Python version:** 3.1.5

**Bandcamp-dl version:** 0.0.7-04

**url:**  https://blankbanshee.bandcamp.com/album/blank-banshee-1

**Describe the issue:** Encoding issue with tracks, ('charmap' codec can't encode characters in positions 90-94) Seems to be with non-english characters.
-------------------------

**Comment by Evolution0** [comment]
Bandcamp-dl supports Python version 3.5 and up.

Possibly try downgrading to a version of bandcamp-dl prior to the move away from older versions of Python (Or updating Python itself)

**Comment by ArotaesForgehammer** [comment]
Issue persists even after updating to newest version of Python and verifying that said version of Python is installed.

**Comment by Evolution0** [comment]
I believe I've found the error in both this and #99 however it was something that was a bug/quirk in the standard library (Not one of the modules we use or our code) that was fixed in 3.6.0 (UTF-8 headers) I have an inkling that while you upgraded the new version isn't being *used* (as I can reproduce this bug in 3.5.2 but not 3.6.0)

I know how to fix, just might take a bit.

**Comment by ArotaesForgehammer** [comment]
Issue persists even on update.

> opical-hysteria'charmap' codec can't encode characters in position 97-105: chara
> cter maps to <undefined>
> Downloading failed..

Using Python 3.6.0 and bandcamp-dl version 0.0.7-06

**Comment by Evolution0** [comment]
I can't seem to duplicate this, does it only happen on this new url you are using? (I don't recognize the trackname in your latest error)

**Comment by ArotaesForgehammer** [comment]
It's not limited to that single track, seems to happen with tracks with non-Latin characters in them. For example:

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\[redacted]>bandcamp-dl https://roex1.bandcamp.com/album/geofront
'charmap' codec can't encode characters in position 78-83: character maps to <un
defined>
Downloading failed..

C:\Users\[redacted]>

**Comment by Evolution0** [comment]
```
Python 3.6.0:
C:\Users\Anthony\AppData\Local\Programs\Python\Python36-32\python.exe C:/GitHub/bandcamp-dl/bandcamp_dl/bandcamp_dl.py https://roex1.bandcamp.com/album/geofront
(9/9) [==================================================] :: Finished: 09 - outro

Python 3.5.2:
C:\Users\Anthony\AppData\Local\Programs\Python\Python35-32\python.exe C:/GitHub/bandcamp-dl/bandcamp_dl/bandcamp_dl.py https://roex1.bandcamp.com/album/geofront
(9/9) [==================================================] :: Finished: 09 - outro

Python 3.4.4:
C:\Python34\python.exe C:/GitHub/bandcamp-dl/bandcamp_dl/bandcamp_dl.py https://roex1.bandcamp.com/album/geofront
(9/9) [==================================================] :: Finished: 09 - outro
```

I've had no luck reproducing this at all:
![full album](http://i.imgur.com/O586NaZ.png)

Make 100% sure that an older version of Python isn't still in PATH.

**Comment by ArotaesForgehammer** [comment]
Issue resolved after repairing Python and removing older installations.
